### ISSUE TITLE
Turn off rounding sum

### ISSUE THREAD

**Issue by arvi** [nortakales/vs-code-qalc#21]
Hello,

I just installed Qalc and trying to figure how to sum without rounding. It prints `473 instead of 472.51`

[Sample Usage](https://imgur.com/a/LIQNZXD)

Thanks

**Comment by nortakales** [comment]
Hmm, I may have chosen poor defaults for the settings. Either change `qalc.output.notation` to `auto` or change `qalc.output.precision` to something greater than 0 (whatever precision you want). I'm going to leave this issue open as a reminder to change the defaults, because the current ones lead to unexpected behavior I think.

**Comment by nortakales** [comment]
Default precision changed to `2` in v0.1.11

**Comment by nortakales** [comment]
https://github.com/nortakales/vs-code-qalc/commit/0ad15fef8012d77f4c4862d70cce48c60e65170a
